### ISSUE TITLE
Update guides on configuring and using limits

### ISSUE THREAD

**Issue by sharifsalah** [AcademySoftwareFoundation/opencue.io#112]
From the announcement of the feature on the users mailing list:

A new functionality called Limits was recently merged into the master branch on Github. Limits allow users to specify the maximum number of concurrently running frames associated with that Limit. Limits are specified on the Job Layer and all Frames within that Layer are considered to take 1 limit count. Once the total limit count reaches the configured max value, the dispatcher will stop any additional frames from running until a frame with that limit has completed.

Installation/Updating

To update your install with this change, you'll need to reinstall all OpenCue components. If you are installing from source be sure to update and recompile the proto files. You will also need to update your database with the latest schema migration. The process for doing this is described here, https://www.opencue.io/docs/other-guides/applying-database-migrations.

Use:

Start by configuring a new Limit.

Open CueGui
Load "Limits" view from the "Views/Plugins->Cuecommander" menu.
Click the "Add Limit" button in the Limits view.
Enter a name for the new limit and press "OK".
Right click on the newly created limit and select "Edit Max Value".
Enter the desired maximum number of concurrently running frames for this limit.
Your limit is now configured and ready for use. New submissions will be able select this limit in CueSubmit UI when creating a new job.

Limits can also be added/removed from existing layers by:

Open CueGui
Load the "Monitor Jobs" view from the "Views/Plugins->Cuetopia" menu.
Double click on a job to load its layers.
Right click on the job you'd like to modify limits for.
Click "Properties".
Check/Uncheck limits you'd like enable/disable for this layer.

**Comment by codinggosu** [comment]
Is this issue still relevant? Can I work on this issue?

**Comment by sharifsalah** [comment]
Thanks for the interest @codinggosu! Yes, this issue is still relevant, so  I'll assign it to you.

Please let me know if you have questions about the authoring workflow.

**Comment by codinggosu** [comment]
Should this be part of Documentation -> Other guides?
or a subsection under Documentation -> User Guides -> Monitoring your jobs
I was thinking Documentation -> Other guides, and am currently working on it with that assumption, if you think there's a better place for it please let me know!!

**Comment by sharifsalah** [comment]
The convention we've used until now, is that guides for end users (visual effects artists) go under 'User guides'. Documentation for system administrators and other more technical roles, go under 'Other guides'.

I believe that 'configuring a new Limit' is a task for a system administrator, and that end users might want to apply the limit after it's available. End users might also want to add or remove a limit from existing layers.

So this issue will probably require making changes to both Other guides and User guides. 

Is that helpful?

**Comment by codinggosu** [comment]
Ok!
I will add "configuring a new Limit" to other guides and add "Adding/Removing limits from existing layers" to user guides.

**Comment by codinggosu** [comment]
I have completed a draft guide for  "configuring a new Limit" and wanted to see a preview running locally. I have set up the repository so the `hugo` command works, but after I make changes to the files (add a configure-limit.md file), the website running on localhost:1313 doesn't seem to reflect the change.
I have tried hugo, hugo server, and hugo server --noHTTPCache --disableFastRender --ignoreCache commands but the site doesn't seem to change. Are there additional configurations or settings that I have to change for the changes in file to be reflected in the hugo running on localhost:1313?

**Comment by sharifsalah** [comment]
Are you creating a new doc or updating an existing doc?

If you're creating a new doc, there's an issue I've noticed where setting a date in the future stops Hugo from serving it. I don't think this is a bug, it seems to be a useful (but potentially confusing) way to stop content being visible until some pre-determined time.

To verify Hugo is showing you updates, I suggest you try updating an existing page first just to make sure your development server is working. You shouldn't need any additional flags.

**Comment by codinggosu** [comment]
Thank you so much! That solved the problem

**Comment by codinggosu** [comment]
Draft pr submitted. #171
