### ISSUE TITLE
Improve discoverability of case study

### ISSUE THREAD

**Issue by bcipriano** [AcademySoftwareFoundation/opencue.io#121]
I had a hard time finding the SPI case study just now. I found it in "Concepts" but didn't really expect it there. I guess I assumed concepts is more about defining terminology and basic facts about the project, though maybe my understanding is incomplete here.

Perhaps a new section is in order, for things like case studies / solutions / etc.? For example our GCP solution could fit into this category as well, once there's content from other CSPs to balance it out.

Also I think a blog post announcing and linking to the case study would be a good addition. (I can add this but wanted to get @sharifsalah's thoughts first.)

**Comment by sharifsalah** [comment]
Agreed, improving the discoverability of this page would be good. 

I'm not sure that changing the navigation folder would have much effect though. In my experience, users tend to mostly ignore site navigation. Your behavior wasn't typical of the intended audience as most people won't know the page exists. Most users will discover pages using any of the following:

1 - Links from third-party sites. (We could definitely do with more sites linking to this page and the OpenCue site more generally)
2 - Links from elsewhere on the site. (We're currently linking from the home page and the overview)
3 - Organically though search. (e.g. search for 'OpenCue case' study' - I think this is fairly well covered by out current.
4 - Site search. (Again this is fairly well covered by the current site search - although it would be good to get rid of the ads if we can)


So I would recommend we focus on (1) and (2). I can do a couple of things on this front:

1 - I can add a link from the README.md file on the main OpenCue repo.
2 - I can add a few more links from within other pages on the site.

Yes thanks, if you can add a blog post, that will help with (2).

That said, no objection to creating a 'case studies' section of the site (for an awesome example, see https://kubernetes.io/case-studies/), but it would be good to add a few more case studies and for the reasons I describe in this reply I wouldn't prioritize it until we do.

**Comment by bcipriano** [comment]
> In my experience, users tend to mostly ignore site navigation. Your behavior wasn't typical of the intended audience as most people won't know the page exists.

Very good point, thank you!

> 1 - I can add a link from the README.md file on the main OpenCue repo.

Do you mean, link to the case study? Or some other target on opencue.io?

> Yes thanks, if you can add a blog post, that will help with (2).

Sure thing.

> That said, no objection to creating a 'case studies' section of the site (for an awesome example, see https://kubernetes.io/case-studies/), but it would be good to add a few more case studies and for the reasons I describe in this reply I wouldn't prioritize it until we do.

Ok great, sounds good to me.

**Comment by sharifsalah** [comment]
To answer your question about linking to the case study, I opened https://github.com/AcademySoftwareFoundation/OpenCue/pull/540 to add a link from the project README.md

I'll think about other places we can cross-link from within the site.

**Comment by bcipriano** [comment]
Thanks Sharif. I'll take this issue now to write the blog post.
