### ISSUE TITLE
Publish a blog post about the LA Pipeline Developers Meetup for OpenCue

### ISSUE THREAD

**Issue by sharifsalah** [AcademySoftwareFoundation/opencue.io#127]
Publish a blog post about the recording of the LA Pipeline Developers Meetup for OpenCue.

Link to video: https://www.youtube.com/watch?v=Vh6wtTzEj_E

**Comment by bcipriano** [comment]
Ah sorry I didn't realize this was assigned to you. I went ahead and wrote it up in #134.
