### ISSUE TITLE
Add a note about configuring PyCharm

### ISSUE THREAD

**Issue by sharifsalah** [AcademySoftwareFoundation/opencue.io#143]
Update the contributor guide for the API reference docs based on this note from @bcipriano:

"For anyone using PyCharm, they can set Tools > Python Integrated Tools > Docstrings > Docstring format to "reStructuredText". This will let you use standard PyCharm tools for generating docstrings in this format."

**Comment by apoorvkhare07** [comment]
@bcipriano @sharifsalah Can I work on this issue if it's still relevant and free for taking?

**Comment by sharifsalah** [comment]
Thanks for volunteering, @apoorvkhare07! I've assigned you the issue.

**Comment by sharifsalah** [comment]
This is the relevant guide to update:

https://www.opencue.io/contributing/opencue/build-docs/
