### ISSUE TITLE
Update Getting Started guide with options for specifying a log directory

### ISSUE THREAD

**Issue by bcipriano** [AcademySoftwareFoundation/opencue.io#148]
macOS Catalina makes `/` a [read-only filesystem](https://support.apple.com/en-us/HT210650), preventing new subdirectories from being created there. This means that our default log directory of `/shots` can't be created on macOS, causing the existing Getting Started guide to be hard to follow for macOS users.

We should update the Getting Started guide to specify a custom log directory for any components that need it. This includes:
- Cuebot
  - Use the `CUE_FRAME_LOG_DIR` env var to override this -- can be passed to the Docker container with the `-e` flag. This setting should then become the default log directory, applied to any new jobs that get submitted.
- RQD
  - Update the [Deploying RQD page](https://www.opencue.io/docs/getting-started/deploying-rqd/#before-you-begin) with new `CUE_FS_ROOT` setting, so the log directory gets shared to the host machine.

I think that should be all, but we'll need to test it more and possibly there are some other doc pages that will need to be updated.

Though this fixes a macOS-specific problem, I think providing an example for overriding the log directory will be useful for other platforms as well -- it's probably the first thing that sysadmins will need to figure out how to change once they move from a Getting Started-type deployment to a real production deployment.

**Comment by bcipriano** [comment]
@sharifsalah Interested to hear your thoughts on this one.

**Comment by sharifsalah** [comment]
That plan sounds good @bcipriano.

I'm not really clear on what `CUE_FS_ROOT` does though. Do you want to send an initial PR and I can help with refining and review?

I've also added CUE_FS_ROOT to https://github.com/AcademySoftwareFoundation/opencue.io/issues/131, which I hope
