### ISSUE TITLE
Document project versioning policy

### ISSUE THREAD

**Issue by bcipriano** [AcademySoftwareFoundation/opencue.io#178]
Define our policy on how we create version numbers for OpenCue -- conditions under which we will increment major vs. minor vs. patch number.

**Comment by bcipriano** [comment]
Here's my initial proposal, based on what our current process looks like:

- Major version to be incremented only be agreement of TSC. Major versions will be rare and the TSC will typically coordinate a list of new major features to be included.
- Minor version to be incremented for potentially breaking changes. Notably any database schema changes or changes to the proto files.
- Patch version to be incremented on every commit merged to `master`.

@gregdenton @smith1511 @larsbijl Any thoughts?

**Comment by larsbijl** [comment]
Sounds good to me.

**Comment by to09** [comment]
@bcipriano, Is this has been solved or not? In case of any work remaining I would love to work on it.

**Comment by bcipriano** [comment]
@to09 This is something that one of the project leads needs to write. I'll be working on it soon.

**Comment by to09** [comment]
@bcipriano, Sure
