### ISSUE TITLE
Yes or No button should be changed thier color after Clicking on it.

### ISSUE THREAD

**Issue by PratyushSawan** [AcademySoftwareFoundation/opencue.io#209]
## After submiting the Feeback section answer, button should be changed thier color.
When user is not submiting their feedback button looks like
![image](https://i.ibb.co/LprpNVz/before-submiting.png)
<hr>
After submiting the answer user should know what they submit, But now after submitting the answer feedback section looks like

![image](https://i.ibb.co/wQYCQ10/after-submit.png)

## We have to update the button effect which is choosen by user So, user can know what option they choose in feedback.
New feeback section should be look like
![image](https://i.ibb.co/Gkkvv96/new-button.png)

Can you assign this to me for update.

**Comment by sharifsalah** [comment]
Actually, this would be a useful enhancement for the Docsy project, which this site uses:

https://github.com/google/docsy/

If you're still interested in working on this, please follow up with the Docsy project.
