### ISSUE TITLE
Quick start for Linux - missing yml file for docker-compose

### ISSUE THREAD

**Issue by chunghob** [AcademySoftwareFoundation/opencue.io#227]
## Describe the documentation issue
A clear and concise description of the issue in the document.

In the https://www.opencue.io/docs/quick-starts/quick-start-linux/ docs there is a reference to run the following:
`docker-compose --project-directory . -f sandbox/docker-compose.yml up`

but in the pull from the repo, doesn't have that file, only this: `docker-compose.monitoring.yml`
And running that yml doens't work with the docker-compose cmd.

## Describe the enhancement
A clear and concise description of the  proposed enhancement.

Add the correct file or update the reference to correct file in the docs

## Additional context
Add any other context here.

**Comment by chunghob** [comment]
Found that it is in the root dir of OpenCue and `docker-compose up` should work given the user has the right group permissions.

**Comment by IdrisMiles** [comment]
This is a recent change introduced by this PR (https://github.com/AcademySoftwareFoundation/OpenCue/pull/933), looks like the docs still need to be updated to reflect the update
