### ISSUE TITLE
Quick start for Linux: VERSION is not up to date

### ISSUE THREAD

**Issue by johhnry** [AcademySoftwareFoundation/opencue.io#250]
## Describe the documentation issue
Related to https://github.com/AcademySoftwareFoundation/OpenCue/issues/810#issuecomment-1159536417

In the current state, using `export VERSION=0.2.65` and `sandbox/install-client-archives.sh` gives errors because some files uses Python 2.x syntax.

The documentation is a little bit misleading if you apply the steps one by one.

(it worked with `export VERSION=0.15.22`)

## Describe the enhancement
I don't know if it's possible to get the latest release number on GitHub at build time for the documentation and inject that but either way it should be stated to use the latest release available or how to find the corresponding version that matches the prebuilt OpenCue images of Cuebot and RQD on Docker Hub used in the sandbox environment.

Thanks!

**Comment by michimussato** [comment]
Thanks @bcipriano I'm totally new to OpenCue, so I guess for people me, it is crucial to keep the learning curve as flat as possible or they'll leave (aka offering GOOD documentation). To state the obvious: the website says "Last modified Tuesday, July 9, 2019".

**Comment by johhnry** [comment]
Thanks @bcipriano for making the changes in the documentation!

@michimussato About what you said: "I feel like this is nothing people would want to use in a production environment."
While I agree that a good documentation is needed, I think that Docker is the way to go in terms of ease of deployment. With a single command / docker-compose file you can deploy complicated services without corrupting your system because it's in isolation.
You don't want it to run? Just do `docker-compose down` and you are set!

And it would surprise me if Ansible's learning curve was easier than Docker one ;)

**Comment by bcipriano** [comment]
> Docker is nice (I have no Docker experience) but I feel like this is nothing people would want to use in a production environment.

Definitely the Docker Compose set up is not really meant for production -- just meant for a quick sandbox environment. I agree it's unfortunate that it probably requires learning a bit about Docker which many folks may not be familiar with.

IMO Docker can be good for production, particularly in cloud environments where you can use a managed Kubernetes service like GKE or Amazon's EKS. I have not tried to set up a similar system locally. I know it's possible but I've heard it can be challenging.

> I'm happy to share my Ansible scripts with you in case it might help other small companies and/or not so tech savvy people to create a working OpenCue installation quickly.

I would love to take a look at these!

**Comment by michimussato** [comment]
@johhnry Docker is easy for sure and it opened the door into OpenCue for me I must admit. When I speak about a production environment, I mean network of connected computers - which often also includes one-man-show companies. This is the scenario where I don't see Docker as the first choice - at least not with the single Docker container there is atm where all OpenCue components (including Postgres) run on one single machine is not the most probable one. However, again, I have no clue about Docker, so in case the currently available Docker container allows a multi-computer setup out of the box, then I take everything back I wrote previously :)

@bcipriano I don't have a full understanding of the required environment for a minimal OpenCue setup. From what I understand so far though, the main thing that complicates the set up initially, is Posgres. If I were the one required to set up a minimal environment that works for demo purposes, I'd probably simply leave that part out and ship OpenCue with MySQL. The virtualenv parts seem - apart from the local compilation of some packages - pretty straightforward. However, same as above, in case I write things that are based on wrong assumptions or just pure ignorance, I take everything back :P

I'll link the Ansible scripts somewhere appropriate later.
