### ISSUE TITLE
Shared config directory path on Windows

### ISSUE THREAD

**Issue by nyqvistatwork** [AcademySoftwareFoundation/opencue.io#275]
## Describe the documentation issue
On page [Configuring OpenCue](https://deploy-preview-274--elated-haibt-1b47ff.netlify.app/docs/other-guides/configuring-opencue/#shared-config-directory) the Windows path for the **Shared config directory** is not correct.
Software settings stored in %APPDATA% needs to be in Local, LocalLow or Roaming subfolder.

## Describe the enhancement

Either keep using %APPDATA% with Local:
- On Windows, `%APPDATA%/Local/opencue` (typically `C:/Users/<username>/AppData/Local/opencue`)

Or use %LOCALAPPDATA%:
- On Windows, `%LOCALAPPDATA%/opencue` (typically `C:/Users/<username>/AppData/Local/opencue`)

**Comment by bcipriano** [comment]
Thank you for this!

It's my understanding that `%APPDATA%` typically expands to `C:/Users/<username>/AppData/Roaming/`. [For example.](https://pureinfotech.com/list-environment-variables-windows-10/) Let me know if this is inaccurate for you.

I've updated #274 to add `Roaming/` to the example path.
