### ISSUE TITLE
Add a pull request template

### ISSUE THREAD

**Issue by sharifsalah** [AcademySoftwareFoundation/opencue.io#39]
Add a custom pull request template to help guide contributions to the docs.

**Comment by to09** [comment]
Have you worked on this issue?

**Comment by sharifsalah** [comment]
Hi @to09 I haven't yet had time. Feel free to make a start and your contribution would be very welcome. Before you start a pull request, I encourage you to plan out what you're thinking in this issue.

The idea behind this issue is to provide a small checklist for anyone opening a pull request against this repository. For example, has the contributor reviewed the staged version of the docs using the deploy preview? (this is not very easy to understand for newcomers)

Also, we should mention that the project currently follows the [Google developer documentation style guide](https://developers.google.com/style), so any contributions to the docs must follow that style.

Feel free to suggest other aspects of a pull request template and you might find the PR template for the main OpenCue repo useful:

https://github.com/AcademySoftwareFoundation/OpenCue/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by sharifsalah** [comment]
I forgot to mention @to09, if you want to work on this issue, let us know and we'll assign it to you.

**Comment by to09** [comment]
Yes, I want to work on this issue, please assign it to me.

**Comment by sharifsalah** [comment]
I've assigned the issue to you.

**Comment by to09** [comment]
Thank you, I have started working on this issue, come with the results soon.

**Comment by to09** [comment]
@sharifsalah , Please explain me more about " has the contributor reviewed the staged version of the docs using the deploy preview?".

**Comment by to09** [comment]
![Screenshot from 2020-03-05 00-07-34](https://user-images.githubusercontent.com/45192178/77169390-6b612000-6adf-11ea-84a8-d27d64cfce48.png)
I  have made the PR template, please review and mark if any changes needed.(Refer Screenshot)

**Comment by sharifsalah** [comment]
I just created a test draft pull request (https://github.com/AcademySoftwareFoundation/opencue.io/pull/166) to demonstrate deploy previews.

In the checks for the pull request, see the following check:

<img width="682" alt="Screen Shot 2020-03-20 at 1 48 55 PM" src="https://user-images.githubusercontent.com/6339099/77169658-c9770e80-6ab1-11ea-8640-211ff38fc667.png">

Click **Details**.

That takes you to a preview of the site, with the changes in the pull request.

You can then navigate to the specific page where the change in the pull request applies. In my pull request this is the following page:

https://deploy-preview-166--elated-haibt-1b47ff.netlify.com/blog/2019/12/18/sony-pictures-imageworks-case-study/

All of the above is not going to be very obvious to contributors. So when a contributor creates a pull request, I think it would be good to explain to them to check / review their change in the deployed preview of the site before they as for a review. They can do this using a draft pull request.

Feel free to try this out yourself and let me know if you have questions.

**Comment by sharifsalah** [comment]
By the way, you say you have made a pull request template. Can you link to the pull request in this issue? I don't see it / can't find it.

**Comment by to09** [comment]
I have a draft pull request, Please review it #167

**Comment by to09** [comment]
Please close this issue, this has been resolved.

**Comment by bcipriano** [comment]
@to09 Yes, thank you.

This has been fixed by #167.
