### ISSUE TITLE
Redirect default Netlify subdomain to primary domain

### ISSUE THREAD

**Issue by sharifsalah** [AcademySoftwareFoundation/opencue.io#50]
To improve SEO, redirect the default Netlify subdomain:

https://elated-haibt-1b47ff.netlify.com/

to 

https://opencue.io/

**Comment by bcipriano** [comment]
Is it better to redirect to `www.opencue.io`? I thought the load balancing was supposed to work better due to the way our DNS is set up.

**Comment by sharifsalah** [comment]
Currently www is just an alias for opencue.io: (we can't actually reach www, it just redirects immediately to the root domain)

```
www.opencue.io is an alias for elated-haibt-1b47ff.netlify.com
elated-haibt-1b47ff.netlify.com has address 167.99.129.42
...
```

Ideally yes, if we can configure the DNS per Netlify's recommended configuration, that would offer better performance.

There are two options for configuring DNS:

1. Implement CNAME flattening, ANAME, or ALIAS records for the root domain (which we can't currently implement)
2. Create an A record pointing to the root domain (what OpenCue is using)

As things currently stand, we need to redirect to https://opencue.io/

**Comment by bcipriano** [comment]
That seems a little bit weird?

In services I've used before the `www` `CNAME` record doesn't consistently resolve to a single IP address -- the service it redirects to is able to use this for load balancing and other dynamic routing. So the goal ends up being to point everything to `www`, because this problem with the root record is pretty typical.

That paragraph you've quoted [from the Netlify docs](https://www.netlify.com/docs/custom-domains/#manual-dns-configuration-for-root-and-www-custom-domains) seems to only apply to the root domain -- I think the `CNAME` setup we currently have is actually the ideal setup as long as we can have people using `www` consistently.

**Comment by sharifsalah** [comment]
Perhaps I'm missing something, but I think we're in agreement?

There's a useful [article from Netlify](https://www.netlify.com/blog/2017/02/28/to-www-or-not-www/) that describes the ideal way to configure `www`:

> When you configure a custom domain to point to a Netlify site, we always recommend that you use a CNAME record pointing at <yoursite>.netlify.com

(Which is how www.opencue.io is configured)

As `www` is already an alias for `https://elated-haibt-1b47ff.netlify.com/`, it wouldn't make sense to redirect it back to `www`.

The changes to the `_redirect` file are only really for SEO, so humans won't generally use `https://elated-haibt-1b47ff.netlify.com/` and I don't imagine the load balancing matters much for search bots.

If I sounded confused at any point, it's probably because I found it a bit odd that the browser doesn't display 'www.opencue.io' and instead just redirects to the root domain.

If there's something I'm missing, or that you think I need to do, then do let me know.

**Comment by bcipriano** [comment]
> If I sounded confused at any point, it's probably because I found it a bit odd that the browser doesn't display 'www.opencue.io' and instead just redirects to the root domain.

Yeah, this is my main concern. I assume this redirection is something we've put in place already, right?

That article you linked covers my concern pretty well:

> The problem is that an A record doesn’t let us insert any traffic direction between the end user’s DNS lookup and our infrastructure. So we have no way of routing users to the closest CDN node, and if our main load balancer for some reason goes unresponsive, we have no way of routing traffic coming directly from A records around this.

> Therefore, we strongly recommend that you always host your main site or app on www or any other subdomain (app.example.com is perfectly fine as well). This way you can use a CNAME record for the canonical site URL. You’ll take full advantage of our globally distributed infrastructure and we can automatically route around any localized outage.

Also, it sounds like we can set up an ALIAS record on the root domain. If this is aliased to point at the Netlify app, and Netlify redirects back to the root domain, won't we end up in an infinite-redirect situation?

**Comment by bcipriano** [comment]
> The changes to the _redirect file are only really for SEO

This may be where I'm getting confused -- does this only apply to SEO, or is it applied for humans as well? And if is NOT applied to humans, why is my browser redirecting me every time I visit `www`?

**Comment by sharifsalah** [comment]
Sorry, I think I've overcomplicated things by attempting to make the change described in this issue while the project is also trying to migrate hosting, DNS, ...etc.

To (hopefully) clarify:

- The specific change described in this issue is only for SEO.
- Currently if you visit https://elated-haibt-1b47ff.netlify.com/, the site doesn't redirect. Netlify seems to suggest this might not be desirable for SEO. I should stress I know a little bit about SEO, but am not at all an expert.
- Netlify suggest the following change to (presumably) make sure search engines associate the content at https://elated-haibt-1b47ff.netlify.com/ with OpenCue:
<img width="893" alt="Screen Shot 2019-06-10 at 6 45 41 PM" src="https://user-images.githubusercontent.com/6339099/59215264-b6ddb980-8bb0-11e9-87a2-616baef24ffd.png">

I haven't applied this change, so it **definitely** has nothing to do with your browser redirecting you every time you visit `www` :)

To confuse matters further (sorry), as you know I've been using various other OSS sites with a similar set up to OpenCue as reference points. kuberflow.io, knative.dev, istio.io all redirect `www` to the root domain. So I have been assuming this is normal behavior for Netlify sites. However, kubeflow.org is set up with `www` as the default. My point is, this is all a bit complicated and confusing and much bigger sites than opencue.io are obviously not solving this consistently...

I think things got muddled when we initially set up the aridomain in Netlify:

- opencue.io is set up as the primary
- www.opencue.io is set up to redirect to the primary

I don't recall if this is the default, but again if I did this, I might have just been emulating the settings for some of the other sites I previously mentioned.

From the [Netlify docs](https://www.netlify.com/blog/2017/02/28/to-www-or-not-www/) again:

> The ideal setup that we recommend is to use www or any other subdomain as the canonical domain for your website, but still use a DNS host that supports some form of CNAME on the apex domain.  Our own DNS hosting does this, for instance (and handles configuration automatically for you too!)

I only found this page today, but my understanding is that we want to set www.opencue.io as the primary.

Agreed?

**Comment by bcipriano** [comment]
Agreed -- this is done now.

**Comment by sharifsalah** [comment]
Fixed in https://github.com/AcademySoftwareFoundation/opencue.io/pull/53

**Comment by sharifsalah** [comment]
This was partially fixed, as we previously implemented the redirect in https://github.com/AcademySoftwareFoundation/opencue.io/pull/53.

However it didn't actually work until we migrated everything from `content/en*` to `content/*` in https://github.com/AcademySoftwareFoundation/opencue.io/pull/73

Now fixed and published.
