### ISSUE TITLE
use locale date style

### ISSUE THREAD

**Issue by bcipriano** [AcademySoftwareFoundation/opencue.io#81]
Blog posts, for example <https://www.opencue.io/blog/2019/07/08/opencue-roadmap-at-siggraph/> list their date in the European style -- "08.07.2019" (for me at least, from my workstation in California).

This might be slightly confusing for American folks. If possible it would be great to use the current locale's date style when rendering the page.

**Comment by sharifsalah** [comment]
Ah yes, this is a good point. I think we're just using the default formatting (which is European for some reason).

I don't _think_ we can locale date style, _but_ I think we can override the way the date is displayed to have it looks something like:

Wednesday, April 4, 2020

The relevant Hugo doc is located at:

https://gohugo.io/functions/dateformat/

The file we would override for the blog / release notes:

https://github.com/google/docsy/blob/master/layouts/blog/content.html

**Comment by bcipriano** [comment]
That's a good suggestion -- any format that makes it obvious what is month vs day should work.

**Comment by bcipriano** [comment]
Thanks for the info Sharif!

I noticed `$.Site.Params.time_format_blog` in that file you linked, and it seems we can just update that setting rather than override the whole template -- see PR.

**Comment by sharifsalah** [comment]
Nicely spotted, and much more elegant. Thanks for implementing the fix so quickly!
