### ISSUE TITLE
Add ASWF sizzle real to homepage

### ISSUE THREAD

**Issue by sharifsalah** [AcademySoftwareFoundation/opencue.io#85]
Add the Academy Software Foundation Sizzle Reel - 2019 to the opencue.io homepage (when it's available)

**Comment by bcipriano** [comment]
Tomorrow (Thursday) I'm planning to email the user and dev lists with the new blog posts. It would be great to also have this reel up on the homepage before that goes out.

Let me know if I can help out.

**Comment by sharifsalah** [comment]
We've been asked to put this on hold.

**Comment by sharifsalah** [comment]
Fixed in https://github.com/AcademySoftwareFoundation/opencue.io/pull/88
