### ISSUE TITLE
Add an introduction to Getting started

### ISSUE THREAD

**Issue by sharifsalah** [AcademySoftwareFoundation/opencue.io#91]
The current [index page for getting started](https://www.opencue.io/docs/getting-started/) is a useful URL to link to from other sites that want to show users how to install OpenCue.

This page should provide more context to explain to new users that it might be useful to first read the overview and become familiar with common OpenCue terminology. We should explain the following:

- What the guides in this section cover
- There are a lot of components in OpenCue
- It might be useful to understand how all the components work together (link to [overview](https://www.opencue.io/docs/concepts/opencue-overview/))
- It might be useful to refer to the glossary as you work through the guides (link to [glossary](https://www.opencue.io/docs/concepts/glossary/))

Note: Most of the contents of this page are auto-generated. Anything added to the Markdown file will appear before the auto-generated index of guides.

**Comment by apoorvkhare07** [comment]
@sharifsalah I would like to work on this issue if no one is working on this?

**Comment by sharifsalah** [comment]
Thanks @apoorvkhare07! I'll assign you the issue.

**Comment by apoorvkhare07** [comment]
> # OpenCue getting started guide
> 
> ### This section contains guides for deploying OpenCue, installing its dependencies, an overview of how OpenCue works and the different components of OpenCue. 
> 
> ---
> 
> [OpenCue Overview](https://www.opencue.io/docs/concepts/opencue-overview/)
> An introduction to OpenCue. It might be useful to understand how all the components work together.
> 
> [Glossary](https://www.opencue.io/docs/concepts/glossary/)
> Glossary of common OpenCue terms. You might refer to the glossary as you work through the guides.
> 
> [Components of OpenCue](url)
> There are a lot of components in OpenCue. Read about them here.
> 
> [Setting up the database](https://www.opencue.io/docs/getting-started/setting-up-the-database/)
> Set up the OpenCue database
> 
> [Deploying Cuebot](https://www.opencue.io/docs/getting-started/deploying-cuebot/)
> Deploy Cuebot to a server from source or a Docker image
> 
> [Deploying RQD](https://www.opencue.io/docs/getting-started/deploying-rqd/)
> Deploy RQD to all OpenCue render hosts
> 
> [Checking out the source code](https://www.opencue.io/docs/getting-started/checking-out-the-source-code/)
> Check out the OpenCue source code
> 
> [Installing PyCue and PyOutline](https://www.opencue.io/docs/getting-started/installing-pycue-and-pyoutline/)
> Install the OpenCue Python API and related Python library
> 
> [Installing CueGUI](https://www.opencue.io/docs/getting-started/installing-cuegui/)
> Install CueGUI to monitor, manage, and troubleshoot jobs
> 
> [Installing CueSubmit](https://www.opencue.io/docs/getting-started/installing-cuesubmit/)
> Install CueSubmit to submit render jobs
> 
> [Installing CueAdmin](https://www.opencue.io/docs/getting-started/installing-cueadmin/)
> Install the CueAdmin command-line client


Hi @sharifsalah, I have incorporated the changes you mentioned. This is how I plan to implement them. Let me know the changes required, I'll add them and make the PR accordingly. 
I think we can have a new page to link with OpenCue Components. I will add it after this if you feel that is relevant.

**Comment by apoorvkhare07** [comment]
@bcipriano reviews on the above-mentioned changes?

**Comment by bcipriano** [comment]
@apoorvkhare07 Please send your proposed changes as a pull request, and I can review them from there.

**Comment by apoorvkhare07** [comment]
Ok sure.
